name: CI/CD Pipeline for WordPress on AWS EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    name: Build WordPress Application
    runs-on: ubuntu-latest

    steps:
      # - name: 📥 Checkout Repository
      #   uses: actions/checkout@v3

      - name: 🛠 Install Dependencies (Optional)
        run: |
          echo "No dependencies needed for plain WordPress, but add here if required."
      
      - name: ✅ Code Validation (Optional)
        run: |
          echo "You can run any linting or validation scripts here."

      - name: 🚀 Notify Build Completion
        run: echo "Build phase completed successfully!"

  deploy:
    name: Deploy WordPress to AWS EC2
    runs-on: ubuntu-latest
    needs: build  # Ensures build completes before deployment

    env:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🔑 Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Deploy WordPress Application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/wordpress-repository-kadel
          git pull origin main
          sudo docker-compose down || true
          sudo docker-compose pull
          sudo docker-compose up -d
          EOF

      - name: ✅ Deployment Completed
        run: echo "WordPress successfully deployed on AWS EC2!"
